// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AuivaGS.DbModel.ModelSP
{
    public partial class DeletePostForumResult
    {
        public int ID { get; set; }
        public string status { get; set; }
        public int? Error_Code { get; set; }
    }
}
