// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AuivaGS.DbModel.ModelSP
{
    public partial class GetAllForumResult
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Descrption { get; set; }
        public string CreateDateTime { get; set; }
        public string username { get; set; }
    }
}
