// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AuivaGS.DbModel.ModelSP
{
    public partial class GetCommentToPostResult
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int? User_ID_Comment { get; set; }
        public string Descrption { get; set; }
        public string Title_Forum { get; set; }
        public string CommitCreateDate { get; set; }
        public string username { get; set; }
        public string Expr1 { get; set; }
    }
}
