// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AuivaGS.DbModel.ModelSP
{
    public partial class GetCommenttoProjectResult
    {
        public string image { get; set; }
        public string username { get; set; }
        public string CommentProject { get; set; }
        public string DateTimeCreate { get; set; }
        public int Expr1 { get; set; }
        public int? User_ID { get; set; }
        public int? Project_ID { get; set; }
    }
}
