// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AuivaGS.DbModel.ModelSP
{
    public partial class GetChatForUserIDResult
    {
        public string? username { get; set; }
        public string? image { get; set; }
        public int? User_ID_Resever { get; set; }
        public int? Chat_ID { get; set; }
    }
}
