// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AuivaGS.DbModel.ModelSP
{
    public partial class PostForumRespones
    {
        public string TitleForum { get; set; }
        public string DescriptionForum { get; set; }
    }
}   